### ISSUE TITLE
Packages sometimes fail to install on NPM

### ISSUE THREAD

**Issue by t3dotgg** [pingdotgg/uploadthing#14]
People reported this during stream, haven't had a chance to repro

**Comment by GithubAccountOfDanielDavis** [comment]
There's a potentially relevant comment here: https://github.com/vercel/turbo/issues/1630#issuecomment-1299753909:

> In this scenario you have a pnpm-lock.yaml and a package-lock.json in the root.
> 
> No matter what we attempt to detect it will make somebody unhappy. There is no reasonable way for us to ensure that we guess correctly in this situation.
> 
> We provide a method to skip that inference by specifying packageManager and no matter what we decide to do, that will be a requirement in this scenario.

I think this means that the only way to support multiple package managers in a turborepo project is:
1. Remove `"packageManager": "pnpm@7.27.0"` from your `package.json`
2. Add `package-lock.json`, `yarn.lock`, and `pnpm-lock.yaml` to your `.gitignore`
3. Proceed to do the actual testing and debugging to verify your commands all work with each package manager

So.... sounds like sticking with pnpm and closing this issue is the way to go.

**Comment by juliusmarminge** [comment]
> Seems like turbo is seeing pnpm-lock.yaml and pnpm-workspace.yaml and using pnpm as its command

Yes, we use pnpm as our package manager here. You shouldnt use npm or yarn when developing in this repo. I thought the `packageManager` field restricted this? Of maybe npm doesnt respect that 🙄

We dont have a contributing guide but we probably should add some quick steps on how to get going.

Closing this.
