### ISSUE TITLE
getFileUrls returns empty array

### ISSUE THREAD

**Issue by 4nduril** [pingdotgg/uploadthing#162]
Hi, when I try to get the url for a given file key (that exists), `getFileUrls` will return only an empty array.
I tried in my next app via an API route but replicated it with Postman so it's not a problem with the package but with the uploadthing server. I set my Secret  as the `x-uploadthing-api-key` header and the version header to 4.1.3. 

Can I  do something to help or am I maybe Doing It Wrong™?

**Comment by markflorkowski** [comment]
So sorry about this, I will look into it today. As a workaround, you can construct the file urls manually using the key:

`const fileUrl =  `https://uploadthing.com/f/${encodeURIComponent(fileKey)}`

This may change with some upcoming features, which is why we want the api functions available, but this should at least unblock you until I am able to resolve the root issue.

**Comment by markflorkowski** [comment]
OK, I believe I found the issue. Doing a few more tests, and will update once the fixes are live!

**Comment by markflorkowski** [comment]
Should be resolved now!

**Comment by 4nduril** [comment]
Awesome! Thanks for the quick answer and fix! I verified it's working now as expected.
