### ISSUE TITLE
Question: How are files handled that are too big?

### ISSUE THREAD

**Issue by 4nduril** [pingdotgg/uploadthing#163]
Hi. I played with files larger than the configured limit and noticed that of course the s3 upload fails and I can do something in the UI with `onUploadError`. But I think I would like to have either the UI component or at least my own UT router telling me that the file I am about to upload is too big for the set limit, before even the S3 upload is tried. 

Also, when that upload fails, my Next server is still polling over 20 times if the upload is done while some part of the app should know that this is not going to happen. The file is then also listed in the UT Dashboard with a size of 0 and status "Uploading" and never gets removed. Since I don't get the key back I also can not remove it from there programmatically.

So is there a way to bail earlier and cleaner when the file(s) to upload are too large?

**Comment by markflorkowski** [comment]
I am definitely going to need to think more on this behavior. I agree though, there should be an indication in UI that a file has exceeded the size limit before the upload starts.

The polling only happens in dev, since we cannot send a webhook to your local environment. So, assuming we do put some blocks in place on the client, that will be a bit difficult to resolve if you were to manage to get past the block and upload a file anyway. 

Re: files in dashboard. Will think on this as well. Considered automatically cleaning them up, but it's not clear how long is "too long" since network conditions can vary so much, though we could possibly mark them as "failed" after something like 12 hours, at which point they are still able to complete technically and then provide a way to flush out failed uploads (both in dash and programmatically)

**Comment by 4nduril** [comment]
> The polling only happens in dev, since we cannot send a webhook to your local environment. 

Ah yes, of course. Then this is no problem.

I also don't know exactly how all the parts play together and where would be the best place to make the overall behavior a bit better. E.g. I don't know why the indication for a file is created in the UT dashboard before the upload is done.
But anyway thanks for thinking further about this one. When I have a new idea I'll be posting it here.

**Comment by jcohenho** [comment]
Any update on this? I'd also like to have the UI display that the upload size limit has been exceeded, currently the error produced by `onUploadError` gives us a vague `Error: Failed to upload file the_img.JPG to S3` error.

**Comment by markflorkowski** [comment]
The next release should have better error messages (#260 ) , and I am hoping to get #189 in as well, which will update the status to `Failed` in the dashboard.

**Comment by jcohenho** [comment]
I'm also noticing there's a couple seconds pause after uploading the file and then rendering it, maybe the progress bar finishes too early?

**Comment by markflorkowski** [comment]
> Maybe this is worthy of its own issue, but I thought I'd mention here first.

Yeah this is definitely worthy of a new issue.

>Otherwise, it shouldn't keep both files in the component, it should remove the one that actually got uploaded. And we should be able to get the knowledge that some files did succeed (and which), so we can update accordingly.

Agreed. I think it might make sense for this to be an option, to try to upload as many files as possible, and let the FE know which succeeded/failed, or to fail and block if it is not possible to upload all of the files

**Comment by markflorkowski** [comment]
presigned urls are no longer returned if your upload request will exceed the quota of your account.
