### ISSUE TITLE
Question: Using on server

### ISSUE THREAD

**Issue by MathiasGruber** [pingdotgg/uploadthing#168]
Thanks for a wonderful library and service. For my usecase, I'm currently generating images on the backend (using some AI stuff), which I'm then pushing to S3, i.e. the following:

```typescript
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

/**
 * Uploads a given remote image URL to S3 under a given key
 * @param url - URL of image to upload to S3
 */
export const uploadAvatar = async (url: string, key: string) => {
  // Get image from replicate
  const res = await fetch(url);
  const blob = await res.arrayBuffer();
  // Upload to S3
  const s3Client = new S3Client({});
  const uploadCommand = new PutObjectCommand({
    Bucket: process.env.AWS_S3_BUCKET_NAME,
    Key: key,
    Body: new Uint8Array(blob),
  });
  const expectedUrl = `https://${process.env.AWS_S3_BUCKET_NAME}.s3.${process.env.AWS_REGION}.amazonaws.com/${key}`;
  const result = await s3Client.send(uploadCommand);
  return result.$metadata.httpStatusCode == 200 ? expectedUrl : null;
};
```
Is there any easy way this library can be used like this on the backend? I kinda want to get rid of the aws-sdk library completely from my codebase

**Comment by markflorkowski** [comment]
Not yet, but we are working on something for this and hope to release it very soon 👍

**Comment by michaelschufi** [comment]
Sounds great! :D

I would like to quickly provide my use case as well:

1. People fill out a form and upload images to a third-party service.
2. My app imports those form responses into the app's database.
3. Users of the app should be able to update those images if necessary.

I import everything because the third-party service does not provide the ability to extend/correct the responses.

So for the update (step 3) I can currently use UploadThing. But I cannot yet store images without the upload form (step 2) in UploadThing.
