### ISSUE TITLE
[Question]: How do I make it upload when I click a button other than uploading immediately?

### ISSUE THREAD

**Issue by Winter100** [pingdotgg/uploadthing#206]
### What happened?

"use client";

import { UploadButton } from "@/utils/uploadthing";
import "@uploadthing/react/styles.css";

export default function UploadBtn() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <UploadButton
        endpoint="imageUploader"
        onClientUploadComplete={(res) => {
          // Do something with the response
          console.log("Files: ", res);
          alert("Upload Completed");
        }}
        onUploadError={(error: Error) => {
          // Do something with the error.
          alert(`ERROR! ${error.message}`);
        }}
      />
    </main>
  );
}

### What did you expect to happen?

Sorry, newbie question. After rendering the code above, when I click the Choose File button and select the image, it uploads immediately. But I want the image to be uploaded when I select it and click the button I created. How can I do this?

### Version

.

### Reproduction Steps

.

### Reproduction Repository

.

### Relevant log output

```bash
.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
The upload button that we provide will always upload immediately. If you would like to have a file selection, then a separate button that you need to click in order to actually upload the file, you will need to use the `useUploadThing()` hook, and create your own component. 

An example of something similar might be [this example](https://github.com/pingdotgg/uploadthing/blob/main/examples/appdir/src/app/image-crop/image-cropper.tsx) which is a bit more complicated as it involves image manipulation, but the idea is the same.
