### ISSUE TITLE
Question:  How to delete the file I uploaded?

### ISSUE THREAD

**Issue by jsvelte** [pingdotgg/uploadthing#253]
### What happened?

The docs process are all about the uploaded in button or dropzone but didn't include how to delete those uploaded file in each users

### What did you expect to happen?

I want something rollback to delete if ever I want to delete the file before I want to post it

### Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mr0Bread** [comment]
You can delete files either from dashboard or using an API. Please, refer following doc section: https://docs.uploadthing.com/api-reference/server#utapi

**Comment by Mr0Bread** [comment]
The utapi have to be handled on server, because it relies on UT env variable available only on side of the server. Therefore, to be able to use it, you have to have your own API endpoint, which you can call. 

On the other side, from what I understand, you have ability to preview the post before the sharing and if the post is not going to be shared, you need to delete the uploaded file. You can approach your problem differently, and upload file only when the user clicks SHARE button. To display the preview of the image, you can 'upload' it to the browser and keep the file in the state of your component

Refer following docs: https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#Example.3a.c2.a0Showing_thumbnails_of_user-selected_images
Here are the docs that help building custom component for controlled upload behavior: https://docs.uploadthing.com/api-reference/react#generatereacthelpers

**Comment by jsvelte** [comment]
@Mr0Bread Hi thank you... I already solved that problem which I only upload the file during clicking the share button and everything seems look fine.

Now I have other question in which if I somehow want to delete the post. I also need to delete it directly in the uploadthing service since you mentioned that it only works on server side. Do you have any hooks that works in client side in order to delete the file in the uploadthing service?

**Comment by Mr0Bread** [comment]
@jsvelte It would be unsafe to provide such access on frontend. Your file storage is your private ground and protected behind auth process. That's why you need ENV variables to successfully perform operations like upload and deletion. Exposing your ENV variables to the public would create a risk of leaking those. With those in possession, anyone could access your storage.

To delete files you can refer following doc page https://docs.uploadthing.com/api-reference/server#deletefiles. You may want to store file key of each post image that was uploaded. Then, you could simply have an API endpoint something like `deletePostImage` and pass post id as an argument. On backend, you would fetch respective file key and call UT API to delete respective file from the storage

**Comment by jsvelte** [comment]
@Mr0Bread so means that everything happens on creating another instance like `deletePostImage`. Because I was thinking that, since the file uploaded in the `uploadthing` generated unique somewhat like ID in the url and I thought that could be the url that I need to delete in the uploadthing service. I will try other away around. Thank you @Mr0Bread  for your reponse. By the way when I upload file in `uploadthing` I only get the url of it.

**Comment by markflorkowski** [comment]
> By the way when I upload file in uploadthing I only get the url of it.

What version of the uploadthing package are you using? You should get back the url, key, size, and name properties when you upload if you are on the latest version of the package.

**Comment by jsvelte** [comment]
@markflorkowski I installed the latest version of the package which is ^5.2.0 and I mean by I only get the url is that in my database I only saved the urls of the uploaded files in uploadthing. Now my question is which of these url, key, size are the properties to trigger the deletion on the service?. Or in the simplest way to say... How to delete the uploadthing medias using only these unique generated urls, keys?

**Comment by markflorkowski** [comment]
deleteFiles takes in a fileKey or an array of fileKeys and deletes them from the server.

```ts
import { utapi } from "uploadthing/server";
 
await utapi.deleteFiles("2e0fdb64-9957-4262-8e45-f372ba903ac8_image.jpg");
```

If you only have the URL, the key is everything after the `/f/`, though I would highly recommend storing the keys that are returned when you upload files, as it is possible that we may change the url structure in the future to the point where the key is no longer in the file url.

**Comment by jsvelte** [comment]
@markflorkowski I see, Thank you so much for the explanation now I might somehow change my table structure for the media uploads. Thank you again @markflorkowski
