### ISSUE TITLE
'FileRouter' must be all exported or all local.ts(2395)

### ISSUE THREAD

**Issue by ihksanghazi** [pingdotgg/uploadthing#254]
(alias) type FileRouter<TParams extends AnyParams = AnyParams> = {
    [x: string]: Uploader<TParams>;
}
import FileRouter
var FileRouter: any
Individual declarations in merged declaration 'FileRouter' must be all exported or all local.ts(2395)

![bug](https://github.com/pingdotgg/uploadthing/assets/110962816/1f366004-0b18-4455-877a-8efed9d62f60)

**Comment by juliusmarminge** [comment]
Please reopen once you can provide a reproduction repo in order for us to debug what issue you're having.

**Comment by MichaelSandor** [comment]
I ran into a similar issue just now and the solution was to simply have VSCode use the **workspace** version of TypeScript (`5.2.2` for me) rather than the default (`4.8.4` for me).

I believe the root cause here is that `satisfies` was introduced to TypeScript into `4.9` so the default of version of TypeScript that VSCode was using didn't recognize it and showed errors as a result.

**Before**
<img width="627" alt="Screenshot 2023-09-03 at 11 05 43 AM" src="https://github.com/pingdotgg/uploadthing/assets/29845136/71ee145c-67a3-45cb-bde7-0f197a5bf405">

**After**
<img width="618" alt="Screenshot 2023-09-03 at 11 06 09 AM" src="https://github.com/pingdotgg/uploadthing/assets/29845136/f611fccf-03aa-4ee2-831e-9dd787168731">
