### ISSUE TITLE
Dropzone for a single file

### ISSUE THREAD

**Issue by MarkLyck** [pingdotgg/uploadthing#273]
I've just setup UploadThing for my project. But I seem to be running into a silly problem of the Dropzone component being more complex than I want/need it to be, with no way to disable the stuff I don't need.

My use-case is a very simple 1 image upload in a form. I'd like my users to be able to just drag-and-drop the image unto the dropzone, and have it automatically start the upload.

I don't want my users to have to go through a second step of clicking "Upload" once they've already chosen the image. It's unnecessary.

But I don't see any setting to just auto-upload on file select? Can you add this option 🙏

**Comment by MarkLyck** [comment]
Managed to get this working using `useUploadThing` but would be nice if you could use the dropzone component for a super simple scenario like this.

**Comment by Mr0Bread** [comment]
@markflorkowski We could provide a way of passing additional props to `useDropzone` hook. It will provide users with more control over dropzone behaviour. In addition, we could allow passing custom `onDrop` callback which could accept several parameters like acceptedFiles and some callback to programatically start uploading. With that author could have done something like that

```jsx
<UploadDropzone
  dropzone={{
    onDrop: ({ triggerUpload }) => {
      triggerUpload()
    }
  }}
/>
```

What do you think?

P.S. Not pinging Julius since he is on vacation from what I understood

**Comment by markflorkowski** [comment]
I was thinking something more like your second suggestion, a prop for choosing between uploading immediately on drop, or using the "upload" button. 

I think a boolean value is sufficient, as we can get the expected number of files from the endpoint. It does raise the question of if the endpoint accepts "up to X" and you have this option enabled, should there be a button to upload less than the maximum?

**Comment by markflorkowski** [comment]
I am hesitant to expose the onDrop() directly as I feel like the benefit of our components is that they handle simple cases well enough for most people, and if you need more complexity, you can use the hook. We should support the ability to swap between these two behaviours of "immediate upload" and "confirmed upload" though.

**Comment by markflorkowski** [comment]
After thinking about this some more, I think having 3 "modes" for the dropzone makes sense:

- `manual` : Current behaviour, requires user to click "upload" button after selecting files
- `auto` : immediately uploads on file selection
- `threshold`: requires user to click "upload" button, unless they select X or more files, where x is the threshold provided in the config. 

Something along the lines of:

```tsx
<UploadDropzone
    config: {
        mode: 'auto' | 'manual' | 'threshold = 'auto';
        threshold?: number;
    }
/>
```

**Comment by Mr0Bread** [comment]
@markflorkowski your approach looks graceful, really. Though I see that you marked 'auto' mode as default. I guess we should make 'manual' default one to avoid introducing breaking changes. Otherwise, everyone relying on current behavior will face issues after an upgrade

Anyway, will prepare PR with such functionality during next couple of days.

**Comment by Mr0Bread** [comment]
@markflorkowski It appeared to be easier than I thought: #279 

Only thing I'm concerned about is the way of calculating the default threshold, that is being used if none is provided by the user. Not sure if approach implemented right now is fine or not. Further discussion can take place under the PR

**Comment by markflorkowski** [comment]
Just cut a release that includes the changes to the components to allow selecting automatic or manual file uploads.
