### ISSUE TITLE
[Bug]: Solid QuickStart is very broken

### ISSUE THREAD

**Issue by juliusmarminge** [pingdotgg/uploadthing#285]
### What happened?

Following the quickstart guide on Solid, there are quite a few issues:

## 1. Invalid components???

```ts
import { UploadButton, UploadDropzone } from "~/uploadthing/client";

export default function Home() {
  return (
    <main>
      <UploadButton endpoint="profileImage" />
      <UploadDropzone endpoint="profileImage" />
    </main>
  );
}
```

Yet, the page is displaying the Uploader component (twice):

<img width="1197" alt="CleanShot 2023-08-28 at 13 53 45@2x" src="https://github.com/pingdotgg/uploadthing/assets/51714798/cfcefb10-0d8e-4834-a58d-c030ace3351e">

Also note how the styling is pretty bad, not sure if this is intentional or not, but we don't seem to put any default font on?

## Wrong type in the file router:

Since Solid is using the /next entrypoint (not sure why), we get invalid type in our router metadata:

![image](https://github.com/pingdotgg/uploadthing/assets/51714798/df1d3e26-2b7b-449c-a100-742ef93f838b)

The correct type would be a standard `Request` type.

## Invalid file path for API route

In docs (https://docs.uploadthing.com/solid#create-an-api-route-using-the-filerouter), we say to create a file `src/api/uploadthing.ts`, this is however invalid as it should be `src/routes/api/uploadthing.ts`

## Missing dependency for dropzone

I think this might be the `solidjs-dropzone` package's fault, but it seems like they should include `attr-accept` as peerDep as it seems to not resolve that correctly:

<img width="1288" alt="CleanShot 2023-08-28 at 13 57 49@2x" src="https://github.com/pingdotgg/uploadthing/assets/51714798/bc8692dc-c820-4ccc-a7df-a10ecbcad844">

### What did you expect to happen?

The quickstart to produce a working example

### Version

```sh
"@uploadthing/solid": "^5.1.2",
"solid-js": "^1.7.11",
"solid-start": "^0.3.4",
"solidjs-dropzone": "^1.0.0",
"uploadthing": "^5.3.3"
```

### Reproduction Steps

1. Create a bare solid-start app
2. Follow the uploadthing solid guide: https://docs.uploadthing.com/solid
  - Install deps
  - Create router
  - Generate components
  - Create API route
3. Start dev server
4. See a pretty broken page

### Link to reproduction

https://github.com/juliusmarminge/solid-uploadthing-example

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jules-sommer** [comment]
I concur, there is something seriously wrong with the uploadthing packages for SolidJs, I have to import ```createUploadThing``` and type ```FileRouter``` from ```"~/../node_modules/uploadthing/dist/server"``` since the package.json does not resolve the module or types using standard syntax from the docs, which would be as follows:
```ts
import { createUploadThing } from "uploadthing";
``` 
as a result of this the middleware functions are not typed correctly as that file has no member named Middleware, which I presume is the Middleware req, ctx object type?
```ts
Argument of type '(opts: { req: Request; res?: undefined; input: "unsetMarker" & { __brand: "unsetMarker"; }; }) => void' is not assignable to parameter of type 'MiddlewareFn<Record<string, unknown>, { _input: "unsetMarker" & { __brand: "unsetMarker"; }; _metadata: "unsetMarker" & { __brand: "unsetMarker"; }; _runtime: "web"; _errorShape: Json; _errorFn: "unsetMarker" & { ...; }; }>'.
  Type 'void' is not assignable to type 'MaybePromise<Record<string, unknown>>'.ts(2345)
```
The components generated from Uploader via @uploadthing/solid seem to not function in my app despite following the messy docs to my best abilities, it simply opens the dropped files in a new window as though the browser is handling the input and not the inputs - same for the button, it doesn't trigger ```onClientUploadComplete``` callback or do any of the uploadthing things you'd expect from an uploadthing.

Seems like I will be writing my own dropzone file-uploader component, which is disappointing but my project must ship in the next few days and I am stuck, I had uploadthing in the back of my mind thinking it would be as "drop in in 2 minutes and you're off" as advertised, glad I didn't pay for the premium plan before testing, thinking I would need the storage space anyways.

Curious if someone can debug for future, but I need a functional solution in the next few days and uploadthing is just nowhere near functional in SolidJs it seems, and this is just in a dev env let alone in prod.

Don't mean to be too harsh, really love the project and respect to anyone trying to make this package better by giving their time and effort to contributing.
