### ISSUE TITLE
[Bug]: Clicking remove on github email causes an error but is not shown to user

### ISSUE THREAD

**Issue by Gunni** [pingdotgg/uploadthing#657]
### What happened?

1. Sign in using github
2. Was forced to allow github email
3. Add different email
4. Verify different email
5. Make different email default
6. Try to remove github email
7. Observe nothing happens

Browser console show the request has this error:

```json
{
	"errors": [
		{
			"message": "Deleting a linked email address is not allowed",
			"long_message": "This email address is linked to one or more Connected Accounts. Remove the Connected Account before deleting this email address.",
			"code": "delete_linked_identification_disallowed"
		}
	]
}
```

### What did you expect to happen?

I expect to be able to remove my github email.

You should be linking accounts using github user id, not email.

### Version

N/A

### Reproduction Steps

1. Sign in using github
2. Was forced to allow github email
3. Add different email
4. Verify different email
5. Make different email default
6. Try to remove github email
7. Observe nothing happens
8. Look at request in dev tools

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
We should be surfacing this error/preventing you from attempting to remove the email that is coming from a linked github account. Will get that resolved. 

These email addresses cannot be removed because they are populated by the email scope in the oauth flow. We need accounts to have an email address for org invites to work correctly, and therefore cannot remove this scope. Will continue to think on how we can have oauth-only accounts, but it is more of an issue with how our auth provider is built, which is unfortunately largely outside of our control.
