### ISSUE TITLE
feat: Get file content in middleware

### ISSUE THREAD

**Issue by ahkhanjani** [pingdotgg/uploadthing#671]
### Describe the feature you'd like to request

We'd want to make changes to the file before uploading it. For example, compressing the image or cropping it to a specific dimension using sharp, or checking for inappropriate content according to our policies.

### Describe the solution you'd like to see

Optionally channel the file stream through our API for specific routes and expose the file content in the file object.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by markflorkowski** [comment]
Right now, the middleware does not get the files themselves, as that would require ingress/egress from your server resulting in additional cost, rather than the files going directly from client -> storage. We would probably recommend one of the following paths if you wanted to modify files before uploading them:

1. Modify the files on client before passing them to the upload function. [Here is an example of that with image cropping.](https://github.com/pingdotgg/uploadthing/tree/main/examples/with-react-image-crop)

2. Pass the files as form data to your server, then use our UTApi functions to perform the upload after completing whatever processing steps you want to do on the files. 

I think part of the issue here is that "middleware" is a bit of a misnomer for the function on the filerouter, which is something I will be thinking about and how we can clarify that or rename. 

We do also have some plans for the ability to post-process files using plugins, as well as automatic content scanning, but I would not expect that to be released for at least a few more months.

**Comment by ahkhanjani** [comment]
@markflorkowski Thanks for the explanation.

> * Modify the files on client before passing them to the upload function. [Here is an example of that with image cropping.](https://github.com/pingdotgg/uploadthing/tree/main/examples/with-react-image-crop?rgh-link-date=2024-03-06T19%3A03%3A29Z)
> * Pass the files as form data to your server, then use our UTApi functions to perform the upload after completing whatever processing steps you want to do on the files.

We can't trust the client and I think number 2 would result in the same cost as you mentioned. It's doable but I think it can't make use of uploadthing's React library. I think uploadthing handling it as an option would be reasonable. Perhaps we could limit the max file size for these endpoints?

**Comment by markflorkowski** [comment]
> I think number 2 would result in the same cost as you mentioned

It would, which is why we don't build it in, you need to explicitly choose to do this. 

> I think uploadthing handling it as an option would be reasonable. Perhaps we could limit the max file size for these endpoints?

I could be convinced of this, how would you expect this to behave? What would the ideal API look like in your mind?

**Comment by ahkhanjani** [comment]
```ts
const p = createUploadthing({ pipe: true });

export const uploadRouter = {
  pipedRoute: p({
    "image/jpeg": { maxFileSize: "1MB" },
    "image/png": { maxFileSize: "1MB" },
  })
    .middleware(() => ... )
	.onReceivedFromClient((ctx) => {
		// Context like `middleware` but files array objects include a content field.
	})
    .onUploadComplete(() => ... ),
};
```

**Comment by ahkhanjani** [comment]
On the server it could be something like:

```ts
const p = createUploadthing({ pipe: true });

export const uploadRouter = {
  pipedRoute: p({
    "image/jpeg": { maxFileSize: "1MB" },
    "image/png": { maxFileSize: "1MB" },
  })
    .middleware(() => ... )
	.onReceivedFromClient((ctx) => {
		// Context like middleware's but file objects include a content field as buffer/string.
		const newFiles = ctx.files.map((file) => {
			const newContent = sharp(file.content)./* processing */.toBuffer();
			return { ...file, content: newContent };
		})
		return newFiles; // We could return the new files array. Now they get uploaded to S3.
	})
    .onUploadComplete(() => ... ),
};
```

<del>I don't know the uploadthing internals but I think this should be possible. If I'm not mistaken, middleware normally sends an S3 URL to the client, and then waits for a response from S3 that the upload has finished.
It gets very complicated because middleware can't check an unfinished HTTP request for cookies to give the user permission for upload, since we don't want to finish an upload before checking for permissions.
What we could do instead is that now instead of an S3 URL, we return a unique URL for this session. I think this part should be handled by us (the API owner). Create a session for the upload and save it in Redis database (user, token and S3 URL). The next request(s) including the file should contain this token in the header.</del>

As you can see I tried to come up with some smart ideas for security but I don't think that's really possible. I guess we'll just have to force a size limit for now. If only we could use sockets...

**Comment by markflorkowski** [comment]
Closing for now. Will continue to think on it, but I don't foresee us adding this functionality in the near term.
