### ISSUE TITLE
refactor: make `@uploadthing/shared` tree-shakeable

### ISSUE THREAD

**Issue by juliusmarminge** [pingdotgg/uploadthing#726]
### Describe the feature you'd like to request

make `@uploadthing/shared` tree-shakeable (by making `@uploadthing/mime-types` free from sideeffects) to reduce footprint when someone is importing unrelated utils from `@uploadthing/shared`. Currently this isn't possible since `@uploadthing/shared/src/utils.ts` imports `lookup` from mime-types package

See example here (`npm run build`, check `dist/index.js`): https://stackblitz.com/edit/vitejs-vite-g92pkm?file=dist%2Findex.js

### Describe the solution you'd like to see

Remove side-effects: 

https://github.com/pingdotgg/uploadthing/blob/1f74d907accd69964f42126ffffd53712f7ec85b/packages/mime-types/src/index.ts#L30-L34

Set `sideEffects: false` in all package.jsons

### Additional information

a simple `isObject` should not be this big :)

![CleanShot 2024-03-23 at 14 10 26@2x](https://github.com/pingdotgg/uploadthing/assets/51714798/6aef4206-191d-4edc-9d74-9d666322e1fc)

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature! (But I wont for a while, anyone pick this up!!!)

**Comment by ertucode** [comment]
I have implemented this at [my fork](https://github.com/ertucode/uploadthing/commit/8acfe4fc08b2575b80b262c1cceabea0648daa8a). 

POC stackblitz: https://stackblitz.com/edit/vitejs-vite-ogve7t?file=build.js

But it is a breaking change, and from what I know it has to be a breaking change. I could not figure out a way to do it without it. In my pr `getExtensions()` and `getTypes()` are exported instead of `extensions` and `types`. Is this okay to merge? 

If it is:

While running `pnpm changeset` should this be a minor change since there was no 1.x release of the mime-types package?

**Comment by juliusmarminge** [comment]
As long as it doesnt cause breaking changes on the consumer packages we're fine. `@uploadthing/shared` doesnt have to follow semver as it's for internal use only
